----------------------------------------------------
----------------TABELA CHAVE------------------------
----------------------------------------------------
CREATE TABLE controle_chave.CHAVE(
CD_CHAVE INT NOT NULL,
DS_CHAVE VARCHAR(30) NOT NULL,
CD_CATEGORIA INT NOT NULL,
TP_STATUS VARCHAR(1) NOT NULL,
CD_USUARIO_CADASTRO VARCHAR(20) NOT NULL,
HR_CADASTRO TIMESTAMP(6) NOT NULL,
CD_USUARIO_ULT_ALT VARCHAR(20),
HR_ULT_ALT TIMESTAMP(6),

--PRIMARY_KEY
CONSTRAINT PK_CD_CHAVE PRIMARY KEY (CD_CHAVE)

);

--SEQUENCE  

DROP SEQUENCE controle_chave.SEQ_CHAVE;
CREATE SEQUENCE controle_chave.SEQ_CHAVE  
START WITH 1    
INCREMENT BY 1
NOCACHE
NOCYCLE;

SELECT * FROM controle_chave.CHAVE

--------------------------------------------------------
----------------TABELA CATEGORIA------------------------
--------------------------------------------------------
CREATE TABLE controle_chave.CATEGORIA(
CD_CATEGORIA INT NOT NULL,
DS_CATEGORIA VARCHAR(100) NOT NULL,
TP_STATUS VARCHAR(1) NOT NULL,
CD_USUARIO_CADASTRO VARCHAR(20) NOT NULL,
HR_CADASTRO TIMESTAMP(6) NOT NULL,
CD_USUARIO_ULT_ALT VARCHAR(20),
HR_ULT_ALT TIMESTAMP(6),

--PRIMARY_KEY
CONSTRAINT PK_CD_CATEGORIA PRIMARY KEY (CD_CATEGORIA)

);

--SEQUENCE  

DROP SEQUENCE controle_chave.SEQ_CATEGORIA;
CREATE SEQUENCE controle_chave.SEQ_CATEGORIA  
START WITH 1    
INCREMENT BY 1
NOCACHE
NOCYCLE;

SELECT * FROM controle_chave.CATEGORIA

-------------------------------------------------------
----------------TABELA REGISTRO------------------------
-------------------------------------------------------
CREATE TABLE controle_chave.REGISTRO(
CD_REGISTRO INT NOT NULL,
CD_CHAVE INT NOT NULL, -- FK TABELA CHAVE
TP_REGISTRO VARCHAR(1) NOT NULL,
CD_USUARIO_MV VARCHAR(20) NOT NULL,
CD_SETOR_MV INT NOT NULL,
NR_RAMAL VARCHAR(100),
NR_CONTATO VARCHAR(100) NOT NULL,
OBS_REGISTRO VARCHAR(200) NOT NULL,
CD_USUARIO_CADASTRO VARCHAR(20) NOT NULL,
HR_CADASTRO TIMESTAMP(6) NOT NULL,
CD_USUARIO_ULT_ALT VARCHAR(20),
HR_ULT_ALT TIMESTAMP(6),

--PRIMARY_KEY
CONSTRAINT PK_CD_REGISTRO PRIMARY KEY (CD_REGISTRO)

);

--SEQUENCE  

DROP SEQUENCE controle_chave.SEQ_REGISTRO;
CREATE SEQUENCE controle_chave.SEQ_REGISTRO
START WITH 1    
INCREMENT BY 1
NOCACHE
NOCYCLE;

SELECT * FROM controle_chave.REGISTRO